export const oneBookInfoInitialState = {
    id: 0,
    title: '',
    rating: null,
    issueYear: undefined,
    description: undefined,
    publish: undefined,
    pages: undefined,
    cover: undefined,
    weight: undefined,
    format: undefined,
    ISBN: undefined,
    producer: undefined,
    authors: [],
    images: [],
    categories: [],
    comments: [],
    booking: null,
    delivery:null,
    histories: [],
}